# Generated by Django 4.2 on 2023-04-20 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='album title')),
                ('desc', models.TextField(verbose_name='description')),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='release date')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='minimum price')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='artist name')),
                ('desc', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='song title')),
                ('desc', models.TextField(verbose_name='description')),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='release date')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='lyrics')),
                ('plays', models.PositiveIntegerField(default=0, verbose_name='plays')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_bot.album', verbose_name='album')),
                ('artists', models.ManyToManyField(to='music_bot.artist', verbose_name='artists')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='music_bot.artist', verbose_name='artists'),
        ),
    ]
